using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class EnterDoor : MonoBehaviour
{
    private bool enterAllowed;
    private string sceneToLoad;
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.GetComponent<doors_4>())
        {
            sceneToLoad = "Tebak";
            enterAllowed = true;

        }
        else if(collision.GetComponent<doors_2>())
        {
            sceneToLoad = "ProyekGame";
            enterAllowed =  true;
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.GetComponent<doors_4>() || collision.GetComponent<doors_2>())
        {
            enterAllowed = false;
        }
    }

    private void Update()
    {
        if (enterAllowed && Input.GetKey(KeyCode.Return))
        {
            SceneManager.LoadScene(sceneToLoad);
        }
    }


}
